### PR TITLE
Initialize Boilerplate

### PR DESCRIPTION
**Pull request by PaisWillie**
Cloning boilerplate from [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate](https://github.com/joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate)

### CODE REVIEW

**Comment by WajdanF** [comment]
Good PR Willie! Keeping the team on track! Make sure to make smallers commits next time.

**Review by WajdanF — APPROVED** [review]

**Review by HenushanB — APPROVED** [review]
Good boilerplate code. Really well done

**Review by ZahinHossainCS — COMMENTED** [review]
Awesome work

**Comment by hammadpathan** [comment]
Great job!

**Pull request merged**
